import "./globals.css";
import { Bricolage_Grotesque } from "@next/font/google";

const bgFont = Bricolage_Grotesque({ subsets: ["latin"], weight: "400" });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bgFont.className}`}>{children}</body>
    </html>
  );
}
